###
GET http://127.0.0.1:3000/api/ HTTP/1.1
###
POST  http://127.0.0.1:3000/api/booksave HTTP/1.1
Content-Type: : application/json

{
    "genre": "RO",
    "corridor": "A1",
    "id": "ROA10002",
    "author": "Monkey D. Luffy",
    "title": "General Secretary of the Communist Party 2",
    "pubDate": "02-01-1953",
    "status": "1"
}

###
GET http://127.0.0.1:3000/api/borrow HTTP/1.1
###
POST http://127.0.0.1:3000/api/ HTTP/1.1
Content-Type: : application/json

{
    "genre": "RO",
    "corridor": "A1",
    "id": "ROA10002",
    "author": "Monkey D. Luffy",
    "title": "General Secretary of the Communist Party 2",
    "pubDate": "02-01-1953",
    "status": "1"
}
###

###
